### ISSUE TITLE
Bcryptjs problem on CircleCi

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#41] opened 2016-06-29 12:10 UTC
we've been having problems getting the tests to pass on circle when using bcrypt to verify a password

+ on OSX 10.11 the tests work (my computer)
+ on Ubuntu 15.10 @katbow 's computer the tests were failing when comparing passwords using `bcrypt.compare(password, passwordHash, cb)` (the async version) but passed using the sync version (`bcrypt.compareSync(.....)`)
+ on Circle (on both Ubuntu 12.04 & 14.04 build environments) both methods fail 😭 

Has anyone encountered this problem before?

the problem is here
https://github.com/ageuk/companion-app/blob/hapi-login/lib/login/hapiLoginConfig.js#L13

this is the test that fails
https://github.com/ageuk/companion-app/blob/hapi-login/test/server/login.test.js#L34

it returns `wrong password` instead of `good credentials` on circleCi

Any help would be amazing 😄  👾  ✨

**Comment by nelsonic** [comment] 2016-06-29 12:43
dupe of #42

**Closed by nelsonic** 2016-06-29 12:43 UTC
Labels: bug, help wanted, technical
